### ISSUE TITLE
Failed to execute management command 'le on' (code: 12, error: Not Supported)

### ISSUE THREAD

**Issue by project-jj** [fO-000/bluescan#10]
This command "sudo bluescan -m br" is working well.

However, when I execute this command "sudo bluescan -m le, the following errors occur.

<img width="773" alt="스크린샷 2021-02-01 오후 10 03 38" src="https://user-images.githubusercontent.com/77441392/106462673-c0c8d480-64d9-11eb-9eaf-4a7a6585e71a.png">

Could you please let me know how to solve this error?

**Comment by fO-000** [comment]
Maybe your Bluetooth adapter does not support LE.

You can execute the `sudo hcitool lescan` to see what it returns.

**Comment by project-jj** [comment]
Thanks to your help, I was able to solve the problem I was facing.
