### ISSUE TITLE
获取远端 BLE 设备的蓝牙版本信息；ubuntu20.04 -m br --lmp-feature 报错的问题Failed to create ACL connection

### ISSUE THREAD

**Issue by dachuiyang** [fO-000/bluescan#14]
安装完成之后  进行经典蓝牙和ble的扫描都没啥问题 、
---
用蓝牙开发板执行  sudo bluescan -m br --lmp-feature ble的mac地址 这条命令的时候，报了这个错误
![image](https://user-images.githubusercontent.com/28263125/122496853-04eaea80-d01f-11eb-9a78-b6dfe4ec3d5c.png)
![image](https://user-images.githubusercontent.com/28263125/122496918-21872280-d01f-11eb-897a-c7fbbb1b1a6d.png)
用csr4.0 执行同一条命令的时候 直接2小时没有任何回显
这个应该怎么解决哪？
环境ubuntu 20.04 x64虚拟机

**Comment by fO-000** [comment]
BLE 设备没有 LMP feature，LMP feature 应该仅属于 BR/EDR 设备。所以才会建立 ACL connection 失败。

**Comment by dachuiyang** [comment]
![image](https://user-images.githubusercontent.com/28263125/122552850-6cc62300-d069-11eb-8bc9-4cabfaf55722.png)
所以文档里这个截图里面的蓝牙是一个双模蓝牙吗？
还有，如果我想获取ble设备的 蓝牙版本信息，blescan有相关命令吗

**Comment by fO-000** [comment]
1. 截图里的设备至少支持 BR/EDR
2. 翻下协议文档应该能找到获取版本的办法，我先把这个功能当作 feature request 吧。

**Comment by dachuiyang** [comment]
好的 期待大佬做出这个功能

**Comment by fO-000** [comment]
> 如果我想获取ble设备的 蓝牙版本信息

我看了下你提的这个功能。目前，bluescan 获取远端设备 LE LL features 的功能，可用于大致区分 BLE 4.x 和 BLE 5.x。

**Comment by fO-000** [comment]
你能说一下为什么想获取 BLE 设备的蓝牙版本信息吗？是有什么需求吗？还是就是学习目的？
