### ISSUE TITLE
A error occurs when scanning LE LL Features

### ISSUE THREAD

**Issue by hustwyk** [fO-000/bluescan#16]
Hi there,
When I use bluescan to scan LE LL Features, an error like this happens:

`[ERROR] bluescan.le_scan, Status of HCI_LE_Create_Connection command (0x0c) != ControllerErrorCodes.PENDING (0x00). If this problem persists, please restart the Bluetooth service to resolve it.`

I've restarted my bluetooth service and my tested devices, but it does not help at all.
What should I do then, any idea?

**Comment by fO-000** [comment]
The code `0x0c` means "Command Disallowed".  So...

1. Which Bluetooth adapter are you using? Does it support BLE?
2. Are there any previously unreleased connections that occupy your Bluetooth adapter resources?
