### ISSUE TITLE
I bought Oston and found that it doesn't seem to support Kali and Linux

### ISSUE THREAD

**Issue by dringer123** [fO-000/bluescan#18]
I changed three Kali devices, and neither Hcitool nor Bluescan could scan the device (LE, BR). Sometimes, at most one Bluetooth device appeared, but it disappeared after a second scan. However, a random search on my phone turned up dozens of Bluetooth devices. Windows can also scan some devices, but not as many as mobile phones. If you have conditions, go to play store for the next mobile version of the scanner.

**Comment by colabar** [comment]
The Ostran Bluetooth Adapter **OST-105** and `bluescan` work well on my latest Kali virtual machine. You can provide more information, such as outputs of `dmesg` and `lsusb`, so that people can help you solve the problem.
