### ISSUE TITLE
Encountered error while trying to install package. ╰─> pybluez

### ISSUE THREAD

**Issue by wiggigemc489** [fO-000/bluescan#20]
hey/ when i put pip3 install bluescan i get this output:
Building wheels for collected packages: pybluez
  Building wheel for pybluez (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.9
      creating build/lib.linux-x86_64-3.9/bluetooth
      copying bluetooth/btcommon.py -> build/lib.linux-x86_64-3.9/bluetooth
      copying bluetooth/__init__.py -> build/lib.linux-x86_64-3.9/bluetooth
      copying bluetooth/widcomm.py -> build/lib.linux-x86_64-3.9/bluetooth
      copying bluetooth/bluez.py -> build/lib.linux-x86_64-3.9/bluetooth
      copying bluetooth/ble.py -> build/lib.linux-x86_64-3.9/bluetooth
      copying bluetooth/msbt.py -> build/lib.linux-x86_64-3.9/bluetooth
      copying bluetooth/macos.py -> build/lib.linux-x86_64-3.9/bluetooth
      /usr/lib/python3/dist-packages/setuptools/lib2to3_ex.py:36: SetuptoolsDeprecationWarning: 2to3 support is deprecated. If the project still requires Python 2 support, please migrate to a single-codebase solution or employ an independent conversion process.
        warnings.warn(
      Fixing build/lib.linux-x86_64-3.9/bluetooth/btcommon.py build/lib.linux-x86_64-3.9/bluetooth/__init__.py build/lib.linux-x86_64-3.9/bluetooth/widcomm.py build/lib.linux-x86_64-3.9/bluetooth/bluez.py build/lib.linux-x86_64-3.9/bluetooth/ble.py build/lib.linux-x86_64-3.9/bluetooth/msbt.py build/lib.linux-x86_64-3.9/bluetooth/macos.py
      Skipping optional fixer: buffer
      Skipping optional fixer: idioms
      Skipping optional fixer: set_literal
      Skipping optional fixer: ws_comma
      Fixing build/lib.linux-x86_64-3.9/bluetooth/btcommon.py build/lib.linux-x86_64-3.9/bluetooth/__init__.py build/lib.linux-x86_64-3.9/bluetooth/widcomm.py build/lib.linux-x86_64-3.9/bluetooth/bluez.py build/lib.linux-x86_64-3.9/bluetooth/ble.py build/lib.linux-x86_64-3.9/bluetooth/msbt.py build/lib.linux-x86_64-3.9/bluetooth/macos.py
      Skipping optional fixer: buffer
      Skipping optional fixer: idioms
      Skipping optional fixer: set_literal
      Skipping optional fixer: ws_comma
      warning: build_py: byte-compiling is disabled, skipping.
      
      running build_ext
      building 'bluetooth._bluetooth' extension
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/bluez
      x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-FZ7wim/python3.9-3.9.5=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-FZ7wim/python3.9-3.9.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./port3 -I/usr/include/python3.9 -c bluez/btmodule.c -o build/temp.linux-x86_64-3.9/bluez/btmodule.o
      In file included from bluez/btmodule.c:20:
      bluez/btmodule.h:5:10: fatal error: bluetooth/bluetooth.h: No such file or directory
          5 | #include <bluetooth/bluetooth.h>
            |          ^~~~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pybluez
  Running setup.py clean for pybluez
Failed to build pybluez

I tried installing python3- dev but already have it and still can't build pybluez. any ideas?

**Comment by fO-000** [comment]
Have you installed the package mentioned in the [`README->requirements`](https://github.com/fO-000/bluescan#requirements)?

**Comment by wiggigemc489** [comment]
hey, after i had a problem with my entire ubuntu i had to reinstall my whole system, after that i was able to install bluescan using the pip command and it worked. but when i run the bluescan i get this output:
Traceback (most recent call last):
  File "/home/wiggige/.local/bin/bluescan", line 5, in <module>
    from bluescan.__main__ import main
  File "/home/wiggige/.local/lib/python3.8/site-packages/bluescan/__main__.py", line 19, in <module>
    from .br_scan import BRScanner
  File "/home/wiggige/.local/lib/python3.8/site-packages/bluescan/br_scan.py", line 31, in <module>
    from .common import bdaddr_to_company_name
  File "/home/wiggige/.local/lib/python3.8/site-packages/bluescan/common.py", line 28, in <module>
    company_id = items[0].removesuffix('   (hex)')
AttributeError: 'str' object has no attribute 'removesuffix'
I'm fairly new to linux (currently studying but its hard for me to stay focus on my classes because they mostly teach the basics and not programming) would appreciate any kind of help, thanks.

**Comment by fO-000** [comment]
I saw your comment in [issue11](https://github.com/fO-000/bluescan/issues/11#issuecomment-1053334416).

The `removesuffix` is a python3.9 feature, which is not supported in python3.8. I think you installed bluescan using pip with python3.8. See `pip -V`. So even though you have python3.9 installed, bluescan still runs under python3.8.

There are two solutions:

* Solution 1

  If python3.8 is the default python in your system, and you installed python3.9 later, you should install bluescan with `sudo python3.9 -m pip install bluescan`. You may still get an error when executing this install command. See [README->Requirements](https://github.com/fO-000/bluescan#requirements) to solve it. This section mentioned the situation that python3.9 is not the default python.

* Solution 2
  
  The version of the default python in the latest Ubuntu or Kali is 3.9 or higher, so using the latest system could solve the problem.
