### ISSUE TITLE
Pyclui is obfuscated | fail to work in ARM

### ISSUE THREAD

**Issue by tctsourcecode** [fO-000/bluescan#21]
Hi, i'm trying to include this tool on ANDRAX repo's but we have ARM powered devices as a platform and your tool not work just because the package pyclui don't have a "source" available, can you release the source in the repo?

**Comment by fO-000** [comment]
bluescan itself is currently open source, but some of the packages it depends on are not ready for it. If these packages are also open source, then I believe bluescan will run well on ARM.

Also, good luck with your ANDRAX project. I'll try it.

**Comment by johntherippe** [comment]
![Screenshot_20220421-034050_NetHunter_Terminal](https://user-images.githubusercontent.com/31730315/164333450-8daab2f5-c489-47cc-94ec-34c9fb315c1f.png)

**Comment by johntherippe** [comment]
I installed everything correctly but bluescan is not running
How to fix it

**Comment by fO-000** [comment]
Ok, I decided to spend some time letting bluescan run on ARM. When it is done, I will tell you. Before this, I suggest you run it on the X86 machine.

**Comment by fO-000** [comment]
Hi, @johntherippe @tctsourcecode. The new version v0.8.0 of bluescan is already released. Please try it, and see if your problem has been solved.

I have tested it on a Raspberry Pi 4 running Kali 2022.1 aarch64.

![image](https://user-images.githubusercontent.com/10009049/164699768-1bfbc9f7-19e4-438b-baf1-539b2f85f14c.png)
