### ISSUE TITLE
Force repairing

### ISSUE THREAD

**Issue by PowerPress** [fO-000/bluescan#25]
Can this send the LMP forgot client pairing key message to force devices you dont control to pair again? Its possible in the spec looking for a app that can do this to be able to sniff the paring key.

**Comment by fO-000** [comment]
1. `bluescan` now focuses on the Bluetooth Host, while the LMP is implemented in the Bluetooth Controller. Maybe in the future, `bluescan` will do some Bluetooth controller work.
2. Force repairing should be possible to implement in higher layer protocols than LMP, such as HCI, SMP, and even system configuration.
3. If you really want to operate LMP, try [seemoo-lab/internalblue](https://github.com/seemoo-lab/internalblue)
