### ISSUE TITLE
Extended Inquiry Response Data

### ISSUE THREAD

**Issue by playground7** [fO-000/bluescan#3]
Hello,

Thank you so much for your support.

When I run br_scan.py with python3, I could sometimes see "None" as the result of the extended Inquiry response data in the inquiry result.

Do you know why the bluetooth scanner for the classic device sometimes gives "None" even though the extended inquiry response data is exist?

**Comment by fO-000** [comment]
Hi,

I'm glad you like the bluescan v0.2.1. Thank you!

According to "BLUETOOTH CORE SPECIFICATION Version 5.2 | Vol 4, Part E page 2348", the `Extended_Inquiry_Response` parameter has a fixed size, 240 octets. And if a Bluetooth device doesn't use this parameter, it will fill it with 240 `0x00`s.

In this time, bluescan will treat the `Extended_Inquiry_Response`  parameter as `None`.
