### ISSUE TITLE
Service Record

### ISSUE THREAD

**Issue by playground7** [fO-000/bluescan#4]
- Hello,

Thank you so much for your support.

I have a question for you.

After SDP scanning, I can see service records of the specified classic Bluetooth device as follow.

```
Service Record
0x0000 : ServiceRecordHandle (uint32)
                0x00010000
0x0001 : ServiceClassIDList (sequence)
                     .
                     .
                     .
```

I am wondering if what "sequence" does mean in the result of service records?

**Comment by fO-000** [comment]
The value type of ServiceClassIDList is a sequence.
