### ISSUE TITLE
Exception: Can't find the ID of hci0 in rfkill

### ISSUE THREAD

**Issue by unknownPT** [fO-000/bluescan#5]
Hello,

Got exception see details below.

sudo bluescan -m br
Traceback (most recent call last):
  File "/usr/local/bin/bluescan", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/bluescan/__main__.py", line 76, i                         n main
    init(args['-i'])
  File "/usr/local/lib/python3.5/dist-packages/bluescan/__main__.py", line 33, i                         n init
    'rfkill unblock %d' % find_rfkill_devid(iface))
  File "/usr/local/lib/python3.5/dist-packages/bluescan/helper.py", line 28, in                          find_rfkill_devid
    raise Exception("Can't find the ID of %s in rfkill" % dev)
Exception: Can't find the ID of hci0 in rfkill

rfkill list
0: sunxi-bt: Bluetooth
        Soft blocked: no
        Hard blocked: no
1: phy0: Wireless LAN
        Soft blocked: no
        Hard blocked: no
2: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no

How to sort it out?

**Comment by fO-000** [comment]
Hi,

Which version of the bluescan are you using? (`bluescan -v`)

**Comment by unknownPT** [comment]
Its latest version, have installed via command: sudo pip3 install bluescan

My system ubuntu 16.04, and rfkill has no "options" -r -n you have used.

**Comment by fO-000** [comment]
My system is Kali, and the version info of `rfkill` is:

```sh
rfkill --version
# rfkill from util-linux 2.36
```

It supports the `-r` and `-n` options. Please upgrade `rfkill` or the OS to solve this problem.

PS: In Ubuntu 16.04.1, the version info of `rfkill` is `rfkill 0.5-1ubuntu3 (Ubuntu)`.

**Comment by unknownPT** [comment]
> In Ubuntu 16.04.1, the version info of `rfkill` is `rfkill 0.5-1ubuntu3 (Ubuntu)`.

Yes, and this version not support options -r and -n
