### ISSUE TITLE
Install failed with error code 1

### ISSUE THREAD

**Issue by unknownPT** [fO-000/bluescan#6]
Hello,

Have updated to ubuntu 18 and now got isues during install, see log below.

Collecting bluepy>=1.3.0 (from bluescan)
  Downloading https://files.pythonhosted.org/packages/27/91/6cfca10bee9862f93015                                                                413cf9e6a52c3081a71f1518963396a055128f8e/bluepy-1.3.0.tar.gz (217kB)
    23% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√▄                        | 51kB 1.2MB/s eta 0:00                                                                    28% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬                       | 61kB 1.4MB/s eta 0:                                                                    32% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√▄                     | 71kB 1.6MB/s et                                                                    37% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬                    | 81kB 1.6MB/s                                                                     42% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√▄                  | 92kB 1.6M                                                                    46% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬                 | 102kB 1                                                                    51% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√▄               | 112                                                                    56% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬              | 1                                                                    61% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√▄                                                                               65% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬                                                                            70% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√▄                                                                      75% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√                                                                    79% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√                                                                    84% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√                                                                    89% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√                                                                    93% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√                                                                    98% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√                                                                    100% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б                                                                √┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬| 225kB 836kB/s
Collecting pyclui>=0.0.2 (from bluescan)
  Downloading https://files.pythonhosted.org/packages/2f/d5/c417c9c7866d537bef64                                                                dd9c9ad760e87e158d73ed2730ef4961048e7154/pyclui-0.0.2-py3-none-any.whl
Collecting bthci>=0.0.6 (from bluescan)
  Downloading https://files.pythonhosted.org/packages/e8/87/5ee4c1d4682c80fbb327                                                                ae1f07398c63f06b2bb5e5a914d3df446c9c3ea5/bthci-0.0.6-py3-none-any.whl
Collecting docopt>=0.6.2 (from bluescan)
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf57813                                                                6ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting pybluez>=0.23 (from bluescan)
  Downloading https://files.pythonhosted.org/packages/08/9f/e9d93b266d2d1ea98878                                                                0a52a696073ba0a65df65a532165fdf6ff90d0ed/PyBluez-0.23.tar.gz (97kB)
    20% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┼                         | 20kB 945kB/s eta 0:00:0                                                                    31% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬                      | 30kB 1.3MB/s eta                                                                     41% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√█                  | 40kB 1.1M                                                                    52% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┴               | 51k                                                                    62% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√▐                                                                            73% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√                                                                    83% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√                                                                    94% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√                                                                    100% |Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б                                                                √┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬Б√┬| 102kB 803kB/s
Building wheels for collected packages: bluepy, docopt, pybluez
  Running setup.py bdist_wheel for bluepy ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokeni                                                                ze;__file__='/tmp/pip-build-io4byvsq/bluepy/setup.py';f=getattr(tokenize, 'open'                                                                , open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(cod                                                                e, __file__, 'exec'))" bdist_wheel -d /tmp/tmpmuppozknpip-wheel- --python-tag cp                                                                36:
  running bdist_wheel
  running build
  running build_py
  Working dir is /tmp/pip-build-io4byvsq/bluepy
  execute make -C ./bluepy clean
  execute make -C bluepy -j1
  Failed to compile bluepy-helper. Exiting install.
  Command was 'make -C bluepy -j1' in /tmp/pip-build-io4byvsq/bluepy
  Return code was 2
  Output was:
  b"make: Entering directory '/tmp/pip-build-io4byvsq/bluepy/bluepy'\ntar xzf bl                                                                uez-src.tgz\ntouch ./bluez-5.47/lib/bluetooth.c ./bluez-5.47/lib/hci.c ./bluez-5                                                                .47/lib/sdp.c ./bluez-5.47/lib/uuid.c ./bluez-5.47/attrib/att.c ./bluez-5.47/att                                                                rib/gatt.c ./bluez-5.47/attrib/gattrib.c ./bluez-5.47/attrib/utils.c ./bluez-5.4                                                                7/btio/btio.c ./bluez-5.47/src/log.c ./bluez-5.47/src/shared/mgmt.c ./bluez-5.47                                                                /src/shared/crypto.c ./bluez-5.47/src/shared/att.c ./bluez-5.47/src/shared/queue                                                                .c ./bluez-5.47/src/shared/util.c ./bluez-5.47/src/shared/io-glib.c ./bluez-5.47                                                                /src/shared/timeout-glib.c\nmake: pkg-config: Command not found\nmake: pkg-confi                                                                g: Command not found\ncc -L. -g -Wall  -Os -DHAVE_CONFIG_H -I./bluez-5.47/attrib                                                                 -I./bluez-5.47 -I./bluez-5.47/lib -I./bluez-5.47/src -I./bluez-5.47/gdbus -I./b                                                                luez-5.47/btio -I./bluez-5.47/sys  -o bluepy-helper bluepy-helper.c ./bluez-5.47                                                                /lib/bluetooth.c ./bluez-5.47/lib/hci.c ./bluez-5.47/lib/sdp.c ./bluez-5.47/lib/                                                                uuid.c ./bluez-5.47/attrib/att.c ./bluez-5.47/attrib/gatt.c ./bluez-5.47/attrib/                                                                gattrib.c ./bluez-5.47/attrib/utils.c ./bluez-5.47/btio/btio.c ./bluez-5.47/src/                                                                log.c ./bluez-5.47/src/shared/mgmt.c ./bluez-5.47/src/shared/crypto.c ./bluez-5.                                                                47/src/shared/att.c ./bluez-5.47/src/shared/queue.c ./bluez-5.47/src/shared/util                                                                .c ./bluez-5.47/src/shared/io-glib.c ./bluez-5.47/src/shared/timeout-glib.c \nbl                                                                uepy-helper.c:33:10: fatal error: glib.h: No such file or directory\n #include <                                                                glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/att.c:                                                                33:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n                                                                          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/gatt.c:32:10: fatal                                                                 error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~                                                                \ncompilation terminated.\n./bluez-5.47/attrib/gattrib.c:34:10: fatal error: gli                                                                b.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilat                                                                ion terminated.\n./bluez-5.47/attrib/utils.c:30:10: fatal error: glib.h: No such                                                                 file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminat                                                                ed.\n./bluez-5.47/btio/btio.c:37:10: fatal error: glib.h: No such file or direct                                                                ory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.                                                                47/src/log.c:38:10: fatal error: glib.h: No such file or directory\n #include <g                                                                lib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/src/shared/io-                                                                glib.c:30:10: fatal error: glib.h: No such file or directory\n #include <glib.h>                                                                \n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/src/shared/timeout-g                                                                lib.c:22:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\                                                                n          ^~~~~~~~\ncompilation terminated.\nMakefile:30: recipe for target 'bl                                                                uepy-helper' failed\nmake: *** [bluepy-helper] Error 1\nmake: Leaving directory                                                                 '/tmp/pip-build-io4byvsq/bluepy/bluepy'\n"

  ----------------------------------------
  Failed building wheel for bluepy
  Running setup.py clean for bluepy
  Running setup.py bdist_wheel for docopt ... done
  Stored in directory: /home/pi/.cache/pip/wheels/9b/04/dd/7daf4150b6d9b12949298                                                                737de9431a324d4b797ffd63f526e
  Running setup.py bdist_wheel for pybluez ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-io4byvsq/pybluez/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpsmc5iqitpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.6
  creating build/lib.linux-aarch64-3.6/bluetooth
  copying bluetooth/__init__.py -> build/lib.linux-aarch64-3.6/bluetooth
  copying bluetooth/msbt.py -> build/lib.linux-aarch64-3.6/bluetooth
  copying bluetooth/widcomm.py -> build/lib.linux-aarch64-3.6/bluetooth
  copying bluetooth/bluez.py -> build/lib.linux-aarch64-3.6/bluetooth
  copying bluetooth/macos.py -> build/lib.linux-aarch64-3.6/bluetooth
  copying bluetooth/ble.py -> build/lib.linux-aarch64-3.6/bluetooth
  copying bluetooth/btcommon.py -> build/lib.linux-aarch64-3.6/bluetooth
  Fixing build/lib.linux-aarch64-3.6/bluetooth/__init__.py build/lib.linux-aarch64-3.6/bluetooth/msbt.py build/lib.linux-aarch64-3.6/bluetooth/widcomm.py build/lib.linux-aarch64-3.6/bluetooth/bluez.py build/lib.linux-aarch64-3.6/bluetooth/macos.py build/lib.linux-aarch64-3.6/bluetooth/ble.py build/lib.linux-aarch64-3.6/bluetooth/btcommon.py
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  Fixing build/lib.linux-aarch64-3.6/bluetooth/__init__.py build/lib.linux-aarch64-3.6/bluetooth/msbt.py build/lib.linux-aarch64-3.6/bluetooth/widcomm.py build/lib.linux-aarch64-3.6/bluetooth/bluez.py build/lib.linux-aarch64-3.6/bluetooth/macos.py build/lib.linux-aarch64-3.6/bluetooth/ble.py build/lib.linux-aarch64-3.6/bluetooth/btcommon.py
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  running build_ext
  building 'bluetooth._bluetooth' extension
  creating build/temp.linux-aarch64-3.6
  creating build/temp.linux-aarch64-3.6/bluez
  aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./port3 -I/usr/include/python3.6m -c bluez/btmodule.c -o build/temp.linux-aarch64-3.6/bluez/btmodule.o
  In file included from bluez/btmodule.c:20:0:
  bluez/btmodule.h:5:10: fatal error: bluetooth/bluetooth.h: No such file or directory
   #include <bluetooth/bluetooth.h>
            ^~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for pybluez
  Running setup.py clean for pybluez
Successfully built docopt
Failed to build bluepy pybluez
Installing collected packages: bluepy, pyclui, pybluez, bthci, docopt, bluescan
  Running setup.py install for bluepy ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-io4byvsq/bluepy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-r96e5gro-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    Working dir is /tmp/pip-build-io4byvsq/bluepy
    execute make -C ./bluepy clean
    execute make -C bluepy -j1
    Failed to compile bluepy-helper. Exiting install.
    Command was 'make -C bluepy -j1' in /tmp/pip-build-io4byvsq/bluepy
    Return code was 2
    Output was:
    b"make: Entering directory '/tmp/pip-build-io4byvsq/bluepy/bluepy'\ntar xzf bluez-src.tgz\ntouch ./bluez-5.47/lib/bluetooth.c ./bluez-5.47/lib/hci.c ./bluez-5.47/lib/sdp.c ./bluez-5.47/lib/uuid.c ./bluez-5.47/attrib/att.c ./bluez-5.47/attrib/gatt.c ./bluez-5.47/attrib/gattrib.c ./bluez-5.47/attrib/utils.c ./bluez-5.47/btio/btio.c ./bluez-5.47/src/log.c ./bluez-5.47/src/shared/mgmt.c ./bluez-5.47/src/shared/crypto.c ./bluez-5.47/src/shared/att.c ./bluez-5.47/src/shared/queue.c ./bluez-5.47/src/shared/util.c ./bluez-5.47/src/shared/io-glib.c ./bluez-5.47/src/shared/timeout-glib.c\nmake: pkg-config: Command not found\nmake: pkg-config: Command not found\ncc -L. -g -Wall  -Os -DHAVE_CONFIG_H -I./bluez-5.47/attrib -I./bluez-5.47 -I./bluez-5.47/lib -I./bluez-5.47/src -I./bluez-5.47/gdbus -I./bluez-5.47/btio -I./bluez-5.47/sys  -o bluepy-helper bluepy-helper.c ./bluez-5.47/lib/bluetooth.c ./bluez-5.47/lib/hci.c ./bluez-5.47/lib/sdp.c ./bluez-5.47/lib/uuid.c ./bluez-5.47/attrib/att.c ./bluez-5.47/attrib/gatt.c ./bluez-5.47/attrib/gattrib.c ./bluez-5.47/attrib/utils.c ./bluez-5.47/btio/btio.c ./bluez-5.47/src/log.c ./bluez-5.47/src/shared/mgmt.c ./bluez-5.47/src/shared/crypto.c ./bluez-5.47/src/shared/att.c ./bluez-5.47/src/shared/queue.c ./bluez-5.47/src/shared/util.c ./bluez-5.47/src/shared/io-glib.c ./bluez-5.47/src/shared/timeout-glib.c \nbluepy-helper.c:33:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/att.c:33:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/gatt.c:32:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/gattrib.c:34:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/attrib/utils.c:30:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/btio/btio.c:37:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/src/log.c:38:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/src/shared/io-glib.c:30:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\n./bluez-5.47/src/shared/timeout-glib.c:22:10: fatal error: glib.h: No such file or directory\n #include <glib.h>\n          ^~~~~~~~\ncompilation terminated.\nMakefile:30: recipe for target 'bluepy-helper' failed\nmake: *** [bluepy-helper] Error 1\nmake: Leaving directory '/tmp/pip-build-io4byvsq/bluepy/bluepy'\n"

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-io4byvsq/bluepy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-r96e5gro-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-io4byvsq/bluepy/

**Comment by unknownPT** [comment]
$ sudo pip3 install bluescan
Collecting bluescan
  Using cached https://files.pythonhosted.org/packages/71/22/a7420bf63be873f87e5da28f291f0763e9cf8eddde7051ea53fb2d142d33/bluescan-0.2.2-py3-none-any.whl
Collecting pyclui>=0.0.2 (from bluescan)
  Using cached https://files.pythonhosted.org/packages/2f/d5/c417c9c7866d537bef64dd9c9ad760e87e158d73ed2730ef4961048e7154/pyclui-0.0.2-py3-none-any.whl
Collecting pybluez>=0.23 (from bluescan)
  Using cached https://files.pythonhosted.org/packages/08/9f/e9d93b266d2d1ea988780a52a696073ba0a65df65a532165fdf6ff90d0ed/PyBluez-0.23.tar.gz
Collecting bluepy>=1.3.0 (from bluescan)
  Using cached https://files.pythonhosted.org/packages/27/91/6cfca10bee9862f93015413cf9e6a52c3081a71f1518963396a055128f8e/bluepy-1.3.0.tar.gz
Collecting bthci>=0.0.6 (from bluescan)
  Using cached https://files.pythonhosted.org/packages/e8/87/5ee4c1d4682c80fbb327ae1f07398c63f06b2bb5e5a914d3df446c9c3ea5/bthci-0.0.6-py3-none-any.whl
Collecting docopt>=0.6.2 (from bluescan)
Building wheels for collected packages: pybluez, bluepy
  Running setup.py bdist_wheel for pybluez ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-u6j_4ymo/pybluez/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp5y4iz69tpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.6
  creating build/lib.linux-aarch64-3.6/bluetooth
  copying bluetooth/__init__.py -> build/lib.linux-aarch64-3.6/bluetooth
  copying bluetooth/msbt.py -> build/lib.linux-aarch64-3.6/bluetooth
  copying bluetooth/widcomm.py -> build/lib.linux-aarch64-3.6/bluetooth
  copying bluetooth/bluez.py -> build/lib.linux-aarch64-3.6/bluetooth
  copying bluetooth/macos.py -> build/lib.linux-aarch64-3.6/bluetooth
  copying bluetooth/ble.py -> build/lib.linux-aarch64-3.6/bluetooth
  copying bluetooth/btcommon.py -> build/lib.linux-aarch64-3.6/bluetooth
  Fixing build/lib.linux-aarch64-3.6/bluetooth/__init__.py build/lib.linux-aarch64-3.6/bluetooth/msbt.py build/lib.linux-aarch64-3.6/bluetooth/widcomm.py build/lib.linux-aarch64-3.6/bluetooth/bluez.py build/lib.linux-aarch64-3.6/bluetooth/macos.py build/lib.linux-aarch64-3.6/bluetooth/ble.py build/lib.linux-aarch64-3.6/bluetooth/btcommon.py
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  Fixing build/lib.linux-aarch64-3.6/bluetooth/__init__.py build/lib.linux-aarch64-3.6/bluetooth/msbt.py build/lib.linux-aarch64-3.6/bluetooth/widcomm.py build/lib.linux-aarch64-3.6/bluetooth/bluez.py build/lib.linux-aarch64-3.6/bluetooth/macos.py build/lib.linux-aarch64-3.6/bluetooth/ble.py build/lib.linux-aarch64-3.6/bluetooth/btcommon.py
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  running build_ext
  building 'bluetooth._bluetooth' extension
  creating build/temp.linux-aarch64-3.6
  creating build/temp.linux-aarch64-3.6/bluez
  aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./port3 -I/usr/include/python3.6m -c bluez/btmodule.c -o build/temp.linux-aarch64-3.6/bluez/btmodule.o
  In file included from bluez/btmodule.c:20:0:
  bluez/btmodule.h:5:10: fatal error: bluetooth/bluetooth.h: No such file or directory
   #include <bluetooth/bluetooth.h>
            ^~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for pybluez

**Comment by fO-000** [comment]
Did you follow the "Requirements" section in `README.md`?

`sudo apt install libglib2.0-dev libbluetooth-dev`
