### ISSUE TITLE
使用bluescan -h时报错 ‘ModuleNotFoundError : No module named 'scapy'’

### ISSUE THREAD

**Issue by Sudozh** [fO-000/bluescan#8]
请问这是什么导致的啊？

**Comment by fO-000** [comment]
版本 0.3.0 会依赖 scapy。我在上传这个版本的时候忘记自动解决 scapy 依赖了。最新的版本 0.3.1 已经解决了这个问题，`sudo pip3 install -U bluescan` 更新即可。
